###
POST http://localhost:8080/register
Content-Type: application/json

{
    "name":"joao",
    "email":"joao@gmail.com",
    "password":"12345678"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email":"joao@gmail.com",
    "password":"12345678"
}

###
POST http://localhost:8080/product
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzgzNzgwMzUxLCJleHAiOjE3ODM3ODM5NTF9.SVF34jKlSUziIMitiSZNzZ6sIRhj-95G3yWrze-xX0c
Content-Type: application/json

{
    "name":-5,
    "price":7888.555555555555555555555555555,
    "description":"Britania"
}