###
POST http://localhost:8080/register
Content-Type: application/json

{
    "name":"joao",
    "email":"joao@gmail.com",
    "password":"12345678"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email":"joao@gmail.com",
    "password":"12345678"
}

###
GET http://localhost:8080/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzgyNzQ3MTAyLCJleHAiOjE3ODI3NTA3MDJ9.60lO6ZViDMoclDLoSJQeZG1WdGP_-XBTXmp_AyE98LA