###
POST http://localhost:8080/register
Content-Type: application/json

{
    "name":"joao",
    "email":"joao@gmail.com",
    "password":"12345678"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "email":"joao@gmail.com",
    "password":"12345678"
}

###
POST http://localhost:8080/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzgzODgyMDI4LCJleHAiOjE3ODM4ODU2Mjh9.v4zMPRMUJLiZtU2eMd89yGKkF2dTi81S9DuE3HTg-2U


{
    "name":"Ventilador",
    "price":500,
    "description":"Lenovo"
}

###
POST http://localhost:8080/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzgzODgyMDI4LCJleHAiOjE3ODM4ODU2Mjh9.v4zMPRMUJLiZtU2eMd89yGKkF2dTi81S9DuE3HTg-2U
Content-Type: application/json

[
  {
    "productId": 1,
    "quantity": 7,
    "unitPrice": 1000
  },
  {
    "productId": 2,
    "quantity": 7,
    "unitPrice": 1000
  },
  {
    "productId": 3,
    "quantity": 7,
    "unitPrice": 1000
  },
  {
    "productId": 4,
    "quantity": 2,
    "unitPrice": 500
  }

]

###
GET http://localhost:8080/product?page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzgzODgyMDI4LCJleHAiOjE3ODM4ODU2Mjh9.v4zMPRMUJLiZtU2eMd89yGKkF2dTi81S9DuE3HTg-2U

###
GET http://localhost:8080/order/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzgzODgyMDI4LCJleHAiOjE3ODM4ODU2Mjh9.v4zMPRMUJLiZtU2eMd89yGKkF2dTi81S9DuE3HTg-2U

